### ISSUE TITLE
build.sh fails with error: anonymous function called without required argument 'version'

### ISSUE THREAD

**Issue by roybatty2019** [novena-next/nixos-novena#1]
I have a novena laptop and would be happy to try this! I installed the nixos ova appliance in vmware, booted, updated and git cloned this repo. Running build.sh returns the following error:

`[demo@nixos:~/nixos-novena]$ ./build.sh 
unpacking 'https://github.com/NixOS/nixpkgs/archive/770ecb1d3134a7b0e4469eb790836bd837c9f675.tar.gz'...
error: anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/kernel.nix:1:1 called without required argument 'version', at /home/demo/nixos-novena/overlay.nix:13:36
(use '--show-trace' to show detailed location information)`

Adding the '--show-trace' argument doesn't reveal any more information. It could be that I have very little idea what I am doing, I had never even heard of nixos/nix until about two hours ago :)

Any suggestions?

**Comment by sorki** [comment]
It was picking nixpkgs from your local channel where `lib/kernel.nix` expected version argument. Now it uses pinned like the rest. Let me know how it goes - I'm hanging on #novena@freenode.
